<?php
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

$sum = 0;
$fib_num = 0;
$last_fib_num = 1;
$current_fib_num = 1;

while ($fib_num < 4000000)
{
    $fib_num = $last_fib_num + $current_fib_num;
    $last_fib_num = $current_fib_num;
    $current_fib_num = $fib_num;
    
    if ($fib_num % 2 === 0)
        $sum += $fib_num;
}      
print("Sum = " + $sum);      
?>